sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mysql123456

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tA4ZVScSuDVqdTXXvsD
    access-key-secret: M9eUVUClk0tK6Ua1oF4cIx1QjGZsSU
    bucket-name: xz-bucket-first
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx57208f01f0fbdff9
    secret: c29243a81d9419121d2c5e2371b822e6
