sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mysql123456

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tA4ZVScSuDVqdTXXvsD
    access-key-secret: M9eUVUClk0tK6Ua1oF4cIx1QjGZsSU
    bucket-name: xz-bucket-first
